// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWC8QFBXJ491SZQDK_m5Ao5IWRR3jsQCc',
    appId: '1:300127106245:web:db390f8501039652896cac',
    messagingSenderId: '300127106245',
    projectId: 'fittrackapp-7b564',
    authDomain: 'fittrackapp-7b564.firebaseapp.com',
    databaseURL: 'https://fittrackapp-7b564-default-rtdb.firebaseio.com',
    storageBucket: 'fittrackapp-7b564.appspot.com',
    measurementId: 'G-BQXN8PPB54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa6lBnPQJuCCC-i54CM1NIieR5wJhbM6E',
    appId: '1:300127106245:android:14bb376002dbc4ca896cac',
    messagingSenderId: '300127106245',
    projectId: 'fittrackapp-7b564',
    databaseURL: 'https://fittrackapp-7b564-default-rtdb.firebaseio.com',
    storageBucket: 'fittrackapp-7b564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPmSeMg-VL1I9DuZafXEcl3cp9ak1BZkM',
    appId: '1:300127106245:ios:865350e88cf0fe15896cac',
    messagingSenderId: '300127106245',
    projectId: 'fittrackapp-7b564',
    databaseURL: 'https://fittrackapp-7b564-default-rtdb.firebaseio.com',
    storageBucket: 'fittrackapp-7b564.appspot.com',
    iosClientId: '300127106245-ili2suaui3ghcf43q7uov8crq3jvq982.apps.googleusercontent.com',
    iosBundleId: 'se.slethware.fittrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPmSeMg-VL1I9DuZafXEcl3cp9ak1BZkM',
    appId: '1:300127106245:ios:865350e88cf0fe15896cac',
    messagingSenderId: '300127106245',
    projectId: 'fittrackapp-7b564',
    databaseURL: 'https://fittrackapp-7b564-default-rtdb.firebaseio.com',
    storageBucket: 'fittrackapp-7b564.appspot.com',
    iosClientId: '300127106245-ili2suaui3ghcf43q7uov8crq3jvq982.apps.googleusercontent.com',
    iosBundleId: 'se.slethware.fittrack',
  );
}
